repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.17
    hooks:
      - id: uv-lock
        description: "Make sure uv.lock is up to date"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        description: "Ruff linting"
        types_or: [python, pyi, jupyter]
        args: [--fix, --exit-non-zero-on-fix, --config=pyproject.toml]
      - id: ruff-format
        description: "Ruff formatting"
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        description: "Run mypy"
        types_or: [python, pyi, jupyter]
        args: [--config-file=pyproject.toml]
